#!/usr/bin/env bash

set -e
set -x

# install skdownscale
/srv/conda/envs/notebook/bin/python -m pip install --upgrade git+git://github.com/pydata/xarray.git@e8bd8665e8fd762031c2d9c87987d21e113e41cc --no-deps
/srv/conda/envs/notebook/bin/python -m pip install --upgrade git+git://github.com/jhamman/scikit-downscale.git@1d451a5d12473dd50bc8d979b98078db9392b3f0 --no-deps

# install jupyter labextensions
jupyter labextension install --clean \
    @jupyter-widgets/jupyterlab-manager \
    dask-labextension

# add dask config
mkdir -p ${KERNEL_PYTHON_PREFIX}/etc/dask
cp .binder/dask_config.yaml ${KERNEL_PYTHON_PREFIX}/etc/dask/dask.yaml
